/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EbooksRouteImport } from './routes/ebooks'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AuthorsRouteImport } from './routes/authors'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EbooksEbookIdReadRouteImport } from './routes/ebooks.$ebookId.read'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EbooksRoute = EbooksRouteImport.update({
  id: '/ebooks',
  path: '/ebooks',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsRoute = AuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EbooksEbookIdReadRoute = EbooksEbookIdReadRouteImport.update({
  id: '/$ebookId/read',
  path: '/$ebookId/read',
  getParentRoute: () => EbooksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authors': typeof AuthorsRoute
  '/books': typeof BooksRoute
  '/catalog': typeof CatalogRoute
  '/ebooks': typeof EbooksRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/ebooks/$ebookId/read': typeof EbooksEbookIdReadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authors': typeof AuthorsRoute
  '/books': typeof BooksRoute
  '/catalog': typeof CatalogRoute
  '/ebooks': typeof EbooksRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/ebooks/$ebookId/read': typeof EbooksEbookIdReadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authors': typeof AuthorsRoute
  '/books': typeof BooksRoute
  '/catalog': typeof CatalogRoute
  '/ebooks': typeof EbooksRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/ebooks/$ebookId/read': typeof EbooksEbookIdReadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authors'
    | '/books'
    | '/catalog'
    | '/ebooks'
    | '/forgot-password'
    | '/loans'
    | '/login'
    | '/members'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/ebooks/$ebookId/read'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authors'
    | '/books'
    | '/catalog'
    | '/ebooks'
    | '/forgot-password'
    | '/loans'
    | '/login'
    | '/members'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/ebooks/$ebookId/read'
  id:
    | '__root__'
    | '/'
    | '/authors'
    | '/books'
    | '/catalog'
    | '/ebooks'
    | '/forgot-password'
    | '/loans'
    | '/login'
    | '/members'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/ebooks/$ebookId/read'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorsRoute: typeof AuthorsRoute
  BooksRoute: typeof BooksRoute
  CatalogRoute: typeof CatalogRoute
  EbooksRoute: typeof EbooksRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoansRoute: typeof LoansRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebooks': {
      id: '/ebooks'
      path: '/ebooks'
      fullPath: '/ebooks'
      preLoaderRoute: typeof EbooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebooks/$ebookId/read': {
      id: '/ebooks/$ebookId/read'
      path: '/$ebookId/read'
      fullPath: '/ebooks/$ebookId/read'
      preLoaderRoute: typeof EbooksEbookIdReadRouteImport
      parentRoute: typeof EbooksRoute
    }
  }
}

interface EbooksRouteChildren {
  EbooksEbookIdReadRoute: typeof EbooksEbookIdReadRoute
}

const EbooksRouteChildren: EbooksRouteChildren = {
  EbooksEbookIdReadRoute: EbooksEbookIdReadRoute,
}

const EbooksRouteWithChildren =
  EbooksRoute._addFileChildren(EbooksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorsRoute: AuthorsRoute,
  BooksRoute: BooksRoute,
  CatalogRoute: CatalogRoute,
  EbooksRoute: EbooksRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoansRoute: LoansRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
